const TEXTS = {
    ge: {
        loginHeader: "ავტორიზაცია",
        loginEmailPlaceholder: "ელ-ფოსტა",
        loginPasswordPlaceholder:"პაროლი",
        recoverPassword: "პაროლის აღდგენა",
        loginButton: "შესვლა",
        loginRegisterText: "არ გაქვს ანგარიში? -",
        loginToRegister: " შექმენი",
        userNotFound:"მომხმარებელი ვერ მოიძებნა",
        incorrectPassword: "პაროლი არასწორია",
        loginWelcome:"მოგესალმებით!",
        signUpHeader: "რეგისტრაცია",
        signUpFirstNameplaceholder: "სახელი",
        signUpLastNameplaceholder: "გვარი",
        signUpTelplaceholder: "ტელეფონის ნომერი",
        signUpEmailplaceholder: "ელ-ფოსტა",
        signUpPasswordplaceholder: "პაროლი",
        signUpConfPasswordplaceholder: "გაიმეორეთ პაროლი",
        signUpButton: "დამატება",
        signUpLoginText: "არსებული ანგარიშით ",
        signUpToLogin: "შესვლა",
        signUpSuccess: "თქვენ წარმატებით დარეგისტრირდით!",
        signUpFirstNameError: "ჩაწერეთ სახელი!",
        expensedate: "თარიღი: ",
        expensecategory: "კატეგორია: ",
        expenseamount: "თანხა:",
        expense: "გასავალი:",
        income: "შემოსავალი:",
        expenseedit: "რედაქტირება",
        addExpense : "ხარჯის დამატება",
        min: "მინ:",
        max : "მაქს:",
        filter: "ფილტრი",
        logOut: "გასვლა",
        addExpenseIncome: "შემოსავალი",
        addExpenseExpense: "გასავალი",
        myExpenses : "ჩემი ხარჯები",
        addExpenseError:"შეავსეთ ყველა ველი!",
        all: "ყველა",
        editedSuccess: "წარმატებით შეიცვალა!",
        users : "მომხმარებლები",
        firstName : "სახელი:",
        lastName: "გვარი:",
        email : "ელ-ფოსტა:",
        tel : "ტელეფონი:",
    },

    us: {
        loginHeader: "Sign In",
        loginEmailPlaceholder: "Email",
        loginPasswordPlaceholder: "Password",
        recoverPassword: "Forgot password?",
        loginButton: "Log In",
        loginRegisterText: "Don't have an account? -",
        loginToRegister: " Sign Up",
        userNotFound:"User not found",
        incorrectPassword: "Incorrect password",
        loginWelcome:"Welcome!",
        signUpHeader: "Sign Up",
        signUpFirstNameplaceholder: "FirstName",
        signUpLastNameplaceholder: "LastName",
        signUpTelplaceholder: "Phone Number",
        signUpEmailplaceholder: "Email",
        signUpPasswordplaceholder: "Password",
        signUpConfPasswordplaceholder: "Confirm Password",
        signUpButton: "Submit",
        signUpLoginText: "Have an account? - ",
        signUpToLogin: " Log In",
        signUpSuccess: "You have successfully registered!",
        signUpFirstNameError: "Enter FirstName!",
        expensedate: "Date: ",
        expensecategory: "Category: ",
        expenseamount: "Amount: ",
        expense: "Expense:",
        income: "Income:",
        expenseedit: "Edit",
        addExpense : "Add Expense",
        min: "Min:",
        max : "Max:",
        filter: "Filter",
        logOut: "Log out",
        addExpenseIncome: "Income",
        addExpenseExpense: "Expense",
        myExpenses: "My expenses",
        addExpenseError:"Fill up all inputs!",
        all: "All",
        editedSuccess: "Edited successfully!",
        users : "Users",
        firstName : "Firstname:",
        lastName: "Lastname:",
        email : "Email:",
        tel : "Tel:",
    }
}

export default TEXTS;